import { type NextPage } from "next";
import Head from "next/head";
import { Blog } from "~/sections/homepage/Blog";
import Brand from "~/sections/homepage/Brand";
import Hero from "~/sections/homepage/Hero";
import { Hosting } from "~/sections/homepage/Hosting";
import { Investor } from "~/sections/homepage/Investor";
import { Newsletter } from "~/sections/homepage/Newsletter";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Crypto Guru</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Brand />
        <Investor />
        <Hosting />
        <Blog />
        <Newsletter />
      </main>
    </>
  );
};

export default Home;
